import 'package:cloud_firestore/cloud_firestore.dart';

/// Returns false for future task occurrences generated by the recurrence
/// Cloud Function. Manually created future tasks remain visible.
bool shouldShowTaskToday(Map<String, dynamic> data, {DateTime? now}) {
  if (data['generatedFromTaskId'] == null) return true;

  final dueDate = data['dueDate'];
  if (dueDate is! Timestamp) return true;

  final localNow = now ?? DateTime.now();
  final localDue = dueDate.toDate().toLocal();
  final todayEnd = DateTime(
    localNow.year,
    localNow.month,
    localNow.day,
    23,
    59,
    59,
    999,
  );

  return !localDue.isAfter(todayEnd);
}
