// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvuVwqdrbUhZvaoHhuay91A0pklobUAGw',
    appId: '1:755867602564:android:df257a7a567975b33bbcd1',
    messagingSenderId: '755867602564',
    projectId: 'organizate-26065',
    storageBucket: 'organizate-26065.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCszJiFH7Qi-KRZy-3W1EedRoasre07hHo',
    appId: '1:755867602564:ios:54ee218ff9aba66a3bbcd1',
    messagingSenderId: '755867602564',
    projectId: 'organizate-26065',
    storageBucket: 'organizate-26065.firebasestorage.app',
    iosClientId: '755867602564-vp562db5bujo9gd2mod5p06bj66nhani.apps.googleusercontent.com',
    iosBundleId: 'com.example.organizate',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfuaf9LscIM4MxjalF2webYdkJvzdwOGM',
    appId: '1:755867602564:web:2788764ce72338093bbcd1',
    messagingSenderId: '755867602564',
    projectId: 'organizate-26065',
    authDomain: 'organizate-26065.firebaseapp.com',
    storageBucket: 'organizate-26065.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfuaf9LscIM4MxjalF2webYdkJvzdwOGM',
    appId: '1:755867602564:web:f6dbe869b200920e3bbcd1',
    messagingSenderId: '755867602564',
    projectId: 'organizate-26065',
    authDomain: 'organizate-26065.firebaseapp.com',
    storageBucket: 'organizate-26065.firebasestorage.app',
  );

}